[JType] cleanup

diff --git a/array_includes b/array_includes
--- a/array_includes
+++ b/array_includes
@@ -6,19 +6,19 @@ elif [ "$1" = '--version' ]; then
 	exit 1
 fi
 ##region########################################### GET PATH, DIR, & NAME ###########################################
-readonly MY_PATH=$(realpath "$0")
-MY_DIR=''
-MY_NAME=''
-if [[ "$MY_PATH" =~ ^(.*)/([^/]+)$ ]]; then
-	readonly MY_DIR="${BASH_REMATCH[1]}" MY_NAME="${BASH_REMATCH[2]}"
-else
-	readonly MY_DIR="$HOME" MY_NAME="$0"
-	echo "$MY_NAME: Failed to get dir" 1>&2
-	exit 1
-fi
+# readonly MY_PATH=$(realpath "$0")
+# MY_DIR=''
+# MY_NAME=''
+# if [[ "$MY_PATH" =~ ^(.*)/([^/]+)$ ]]; then
+# 	readonly MY_DIR="${BASH_REMATCH[1]}" MY_NAME="${BASH_REMATCH[2]}"
+# else
+# 	readonly MY_DIR="$HOME" MY_NAME="$0"
+# 	echo "$MY_NAME: Failed to get dir" 1>&2
+# 	exit 1
+# fi
 ##endregion######################################## GET PATH, DIR, & NAME ###########################################
 declare value="$1"
-if ! shift; then exit 1; fi
+if ! shift; then exit 255; fi
 for arg in "$@"; do
 	if [ "$value" = "$arg" ]; then exit 0; fi
 done
