expanded decimal_calc

diff --git a/decimal_calc b/decimal_calc
--- a/decimal_calc
+++ b/decimal_calc
@@ -2,9 +2,10 @@
 
 show_help() {
 	cat << __EOF__
-Print the result of the given division operation with the specified number of trailing decimal places
+Print the result of the given division operation with the specified precision, trimming trailing zeros and rounding excess.
 
 Usage:	$0 NUMERATOR DENOMINATOR [MULTIPLIER SEPARATOR]
+	or:	$0 [-c COARSENESS] [-d decimal] NUMERATOR DENOMINATOR
 	or:	$0 --help
 	or:	$0 --version
 
@@ -17,24 +18,99 @@ $0 1.0.0
 Copyright (C) 2025 Justin Morris
 __EOF__
 }
+declare -i numerator=0; unset numerator
+declare -i denominator=0; unset denominator
+declare coarseInput # ="${coarseInput:-100}"
+declare separator='.'
+while [[ -n "${1+x}" ]]; do
+	case "$1" in
+		(-h | --help)
+			show_help
+			exit
+			;;
+		(-v | --version)
+			show_version
+			exit
+			;;
+		(-c | --coarseness)
+			shift
+			coarseInput="$1"
+			shift
+			;;
+		(-d | --decimal)
+			shift
+			separator="$1"
+			shift
+			;;
+		(*)
+			if [[ -n "${numerator+x}" ]]; then
+				if [[ -n "${denominator+x}" ]]; then
+					if [[ -n "${coarseInput+x}" ]]; then
+						exit 1
+					else
+						coarseInput="$1"
+					fi
+				else
+					((denominator = $1))
+				fi
+			else
+				((numerator = $1))
+			fi
+			shift
+			;;
+	esac
+done
 
-if [ "$1" = '--help' ]; then
-	show_help
-	exit
-elif [ "$1" = '--version' ]; then
-	show_version
+declare -ir numerator
+declare -ir denominator
+if ((denominator==0)); then
+	echo -n "Divide by zero error: $numerator / $denominator" 1>&2
+	exit 1
+fi
+declare -i pre=numerator/denominator
+if (( numerator % denominator == 0 )); then
+	echo -n "$pre"
 	exit
 fi
-declare -ir numerator="$1"
-declare -ir denominator="$2"
-declare -ir pre=numerator/denominator
-declare -r coarseInput="${3:-100}"
-declare -ir coarseness="$((10 ** "${#coarseInput}" / 10))"
+declare -r coarseInput="${coarseInput:-100}"
+declare -ir decimalDigits="${#coarseInput}"
+declare -ir coarseness="$((10 ** decimalDigits))"
 if ((coarseness==1)); then
 	echo -n "$pre"
-	return
+	exit
 fi
-declare separator='.'
-if [[ -n "${4+x}" ]]; then separator="$4"; fi
-declare -i l_intermediate=0; ((l_intermediate=numerator * coarseness / denominator))
-echo -n "$pre$separator$l_intermediate"
+declare -i l_intermediate=0; ((l_intermediate=numerator * coarseness / denominator, pre_count=${#pre})); 
+declare +i l_intermediate
+if ((pre_count > 1 || pre != 0)); then l_intermediate="${l_intermediate:$pre_count}"; fi
+while [[ "${l_intermediate: -1}" == '0' ]] && ((${#l_intermediate} > 1)); do l_intermediate="${l_intermediate:0:-1}"; done
+if (( ${#l_intermediate} >= decimalDigits )); then
+	declare penultimate="${l_intermediate: -2:1}" last="${l_intermediate: -1:1}"; l_intermediate="${l_intermediate:0:-2}" # ((l_intermediate/=100))
+	if ((last<5)); then
+		echo -n "$pre$separator$l_intermediate$penultimate"
+	else
+		while ((penultimate == 9 && ${#l_intermediate} > 0)); do
+			penultimate="${l_intermediate: -1}"
+			l_intermediate="${l_intermediate:0:-1}"
+		done
+		if ((${#l_intermediate} > 0 || penultimate < 9)); then
+			echo -n "$pre$separator$l_intermediate$((penultimate+1))"
+		else
+			((i=${#pre}-1))
+			l_intermediate="${pre:$i:1}"
+			while ((i >= 0 && ${pre:$i:1} == 9 && ${#l_intermediate} > 0)); do
+				l_intermediate="${pre:$i:1}"
+				pre="${pre:0:$i}0${pre:$((i+1))}"
+				((i--))
+			done
+			if ((i < 0 && ${pre:0:1} == 9)); then
+				echo -n "1$pre"
+			else
+				echo -n "${pre:0:$i}$((${pre:$i:1} + 1))${pre:$((i+1))}"
+			fi
+		fi
+	fi
+else
+	echo -n "$pre$separator${l_intermediate:0:$decimalDigits}"
+fi
+
+exit
