Standardizing path retrieval

diff --git a/looper b/looper
--- a/looper
+++ b/looper
@@ -5,7 +5,19 @@ if [ "$1" = '--help' ]; then
 elif [ "$1" = '--version' ]; then
 	exit 1
 fi
-readonly LOGFILE='/home/jmor/reposLocal/custom-shell-scripts/log.txt'
+##region########################################### GET PATH, DIR, & NAME ###########################################
+readonly MY_PATH=$(realpath "$0")
+MY_DIR=''
+MY_NAME=''
+if [[ "$MY_PATH" =~ ^(.*)/([^/]+)$ ]]; then
+	readonly MY_DIR="${BASH_REMATCH[1]}" MY_NAME="${BASH_REMATCH[2]}"
+else
+	readonly MY_DIR="$HOME" MY_NAME="$0"
+	echo "$MY_NAME: Failed to get dir" 1>&2
+	exit 1
+fi
+##endregion######################################## GET PATH, DIR, & NAME ###########################################
+readonly LOGFILE="$MY_DIR/$MY_NAME.log.txt"
 declare -i current_count=0
 # date +'%T %D' >> $LOGFILE
 l_exit() {
diff --git a/misc_util b/misc_util
--- a/misc_util
+++ b/misc_util
@@ -9,16 +9,15 @@ fi
 # #endregion ########## DON'T GEN DOCUMENTATION ##########
 
 ##region########################################### GET PATH, DIR, & NAME ###########################################
-# declare -r MY_PATH="$0"
 readonly MY_PATH=$(realpath "$0")
 MY_DIR=''
 MY_NAME=''
 if [[ "$MY_PATH" =~ ^(.*)/([^/]+)$ ]]; then
-	readonly MY_DIR="${BASH_REMATCH[1]}"
-	readonly MY_NAME="${BASH_REMATCH[2]}"
+	readonly MY_DIR="${BASH_REMATCH[1]}" MY_NAME="${BASH_REMATCH[2]}"
 else
-	readonly MY_DIR="Failed to get dir"
-	readonly MY_NAME="$0"
+	readonly MY_DIR="$HOME" MY_NAME="$0"
+	echo "$MY_NAME: Failed to get dir" 1>&2
+	exit 1
 fi
 ##endregion######################################## GET PATH, DIR, & NAME ###########################################
 
